name: Upload Docker Hub

on: 
  push: 
    tags: ["v[0-9.]+"]

env:
  DOCKER_FILE: docker-compose.yml
  VER: ${{ github.ref_name }}

jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: docker build
        run: docker compose up -f ${{ env.DOCKER_FILE }} build

      - name: check images
        run: docker images

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push / iae-back
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ptjkjm1/iae-back:${{env.VER}}

      - name: Build and Push / iae-front
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ptjkjm1/iae-front:${{env.VER}}
          
