name: Upload Docker Hub

on: 
  push: 
    tags: ["v[0-9.]+"]

env:
  DOCKER_FILE: docker-compose.yml
  VER: ${{ github.ref_name }}

jobs:
  check-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker build
        run: docker compose -f ${{ env.DOCKER_FILE }} up -d

  push-docker:
    needs: [ check-build-docker ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push / iae-front
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./front-react.Dockerfile
          push: true
          tags: ptjkjm1/iae-front:${{env.VER}}

      - name: Push / iae-back
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./fastapi.Dockerfile
          push: true
          tags: ptjkjm1/iae-back:${{env.VER}}
          
